info/__init__.py
from logging.handlers import RotatingFileHandler

import redis
from flask import Flask, app, jsonify
from flask import g
from flask import render_template
from flask.ext.session import Session
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.wtf import CSRFProtect
from flask.ext.wtf.csrf import generate_csrf

from config import *


db=SQLAlchemy()
from info.utils.common import do_index_class, check_user

# redis_store=None #type:StrictRedis
redis_store = None  # type:StrictRedis
#
# redis_store: StrictRedis = None


def set_up_log(u_selected_config):
    # 设置日志的记录等级
    logging.basicConfig(level=seleceted_config[u_selected_config].LOG_LEVEL)  # 调试debug级
    # 创建日志记录器，指明日志保存的路径、每个日志文件的最大大小、保存的日志文件个数上限
    file_log_handler = RotatingFileHandler("logs/log", maxBytes=1024 * 1024 * 100, backupCount=10)
    # 创建日志记录的格式 日志等级 输入日志信息的文件名 行数 日志信息
    formatter = logging.Formatter('%(levelname)s %(filename)s:%(lineno)d %(message)s')
    # 为刚创建的日志记录器设置日志记录格式
    file_log_handler.setFormatter(formatter)
    # 为全局的日志工具对象（flask app使用的）添加日志记录器
    logging.getLogger().addHandler(file_log_handler)





def create_app(u_selected_config):
    app = Flask(__name__)
    set_up_log(u_selected_config)


    app.config.from_object(seleceted_config[u_selected_config])
    app.add_template_filter(do_index_class,"indexClass")
    @app.after_request
    def after_request(response):
        # 调用函数生成 csrf_token
        csrf_token = generate_csrf()
        # 通过 cookie 将值传给前端
        response.set_cookie("csrf_token", csrf_token)
        return response


    CSRFProtect(app)
    Session(app)

    db.init_app(app)
    # db = SQLAlchemy(app)
    # @app.errorhandler(404)
    # @check_user
    # def page_notfound(e):
    #     user=g.user
    #     data={
    #         'user':user.to_dict()
    #     }
    #     return render_template('others/404.html',data=data)




    global redis_store

    redis_store = redis.StrictRedis(host=My_config.REDIS_HOST, port=My_config.REDIS_PORT)
    from info.moduls.index import index_
    from info.moduls.passport import passport_
    from info.moduls.news import news_blu
    from info.moduls.profile import profile_blu
    from info.moduls.admin import admin_blu


    app.register_blueprint(profile_blu)
    app.register_blueprint(index_)
    app.register_blueprint(passport_)
    app.register_blueprint(news_blu)
    app.register_blueprint(admin_blu)
    return app

info/moduls/admin/__init__.py
from flask import Blueprint

admin_blu=Blueprint('admin',__name__,url_prefix="/admin")

from . import views

info/moduls/admin/views.py
import time
from datetime import datetime, timedelta

from flask import current_app, jsonify
from flask import g
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for

from info import check_user, db
from info import constants
from info.models import User, News, Category
from info.utils.response_code import RET
from . import admin_blu

@admin_blu.route('/login',methods=['POST','GET'])
@check_user
def admin_login():
    user=g.user
    if request.method=='GET':
        return render_template('admin/login.html')
    if request.method=='POST':
        password=request.form.get('password')
        name=request.form.get('username')
        if not all([password,name]):
            return render_template('admin/login.html')
        try:
            user=User.query.filter(User.mobile==name,user.is_admin==True).first()
        except Exception as e:
            current_app.logger.error(e)

        if not user:
            return render_template('admin/login.html')

        password_checked=user.check_password(password)
        if not password_checked:
            return render_template('admin/login.html')

        return redirect(url_for('admin.admin_index'))


"主页"
@admin_blu.route('/index')
@check_user
def admin_index():
    user=g.user
    data={
        'user':user.to_admin_dict()
    }
    return render_template('admin/index.html',data=data)


@admin_blu.route('/user_count')
@check_user
def user_count():
    total_count=User.query.filter(User.is_admin==False).count()
    mon_count=1
    day_count=0
    t = time.localtime()
    begin_mon_date_str = '%d-%02d-01' % (t.tm_year, t.tm_mon)
    begin_day_date_str=begin_day_date = datetime.strptime(('%d-%02d-%02d' % (t.tm_year, t.tm_mon, t.tm_mday)), "%Y-%m-%d")
    mon_count=User.query.filter(User.is_admin==False,User.create_time>begin_mon_date_str).count()
    day_count=User.query.filter(User.is_admin==False,User.create_time>begin_day_date_str).count()
    active_time = []
    active_count = []

    # 取到今天的时间字符串
    today_date_str = ('%d-%02d-%02d' % (t.tm_year, t.tm_mon, t.tm_mday))
    # 转成时间对象
    today_date = datetime.strptime(today_date_str, "%Y-%m-%d")

    for i in range(0, 31):
        # 取到某一天的0点0分
        begin_date = today_date - timedelta(days=i)
        # 取到下一天的0点0分,相当与今天的24点
        end_date = today_date - timedelta(days=(i - 1))
        count = User.query.filter(User.is_admin == False, User.last_login >= begin_date,
                                  User.last_login < end_date).count()
        active_count.append(count)
        active_time.append(begin_date.strftime('%Y-%m-%d'))

    # User.query.filter(User.is_admin == False, User.last_login >= 今天0点0分, User.last_login < 今天24点).count()

    # 反转，让最近的一天显示在最后
    active_time.reverse()
    active_count.reverse()

    data = {
        "total_count": total_count,
        "mon_count": mon_count,
        "day_count": day_count,
        "active_time": active_time,
        "active_count": active_count
    }
    return render_template('admin/user_count.html',data=data)



"新闻列表"
@admin_blu.route('/user_list')
@check_user
def user_list():
    user=g.user
    currentPage=request.args.get('page',1)
    totalPage=request.args.get('page',1)
    paginate=User.query.filter(User.is_admin==False).paginate(currentPage,constants.ADMIN_USER_PAGE_MAX_COUNT,False)
    pagenations=paginate.items

    user=[]
    for i in pagenations:
        user.append(i.to_admin_dict())
    data={
        'users':user
    }
    return render_template('admin/user_list.html',data=data)



"新闻审核"
@admin_blu.route('/news_review')
@check_user
def news_review():
    page = request.args.get("p", 1)
    keywords = request.args.get("keywords", None)
    try:
        page = int(page)
    except Exception as e:
        current_app.logger.error(e)
        page = 1

    news_list = []
    current_page = 1
    total_page = 1

    filters = [News.status != 0]
    # 如果关键字存在，那么就添加关键字搜索
    if keywords:
        filters.append(News.title.contains(keywords))
    try:
        paginate = News.query.filter(*filters) \
            .order_by(News.create_time.desc()) \
            .paginate(page, constants.ADMIN_NEWS_PAGE_MAX_COUNT, False)

        news_list = paginate.items
        current_page = paginate.page
        total_page = paginate.pages
    except Exception as e:
        current_app.logger.error(e)

    news_dict_list = []
    for news in news_list:
        news_dict_list.append(news.to_review_dict())

    context = {"total_page": total_page, "current_page": current_page, "news_list": news_dict_list}

    return render_template('admin/news_review.html', data=context)

@check_user
@admin_blu.route('/news_review_action', methods=["POST"])
def news_review_action():
    """新闻管理中的新闻审核详情（点击 按钮之后的页面）"""
    # 1. 接受参数
    news_id = request.json.get("news_id")
    action = request.json.get("action")

    # 2. 参数校验
    if not all([news_id, action]):
        return jsonify(errno=RET.PARAMERR, errmsg="参数错误")

    if action not in("accept", "reject"):
        return jsonify(errno=RET.PARAMERR, errmsg="参数错误")

    # 查询到指定的新闻数据
    try:
        news = News.query.get(news_id)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg="数据查询失败")

    if not news:
        return jsonify(errno=RET.NODATA, errmsg="未查询到数据")

    if action == "accept":
        # 代表接受
        news.status = 0
    else:
        # 代表拒绝
        reason = request.json.get("reason")
        if not reason:
            return jsonify(errno=RET.PARAMERR, errmsg="请输入拒绝原因")
        news.status = -1
        news.reason = reason
    try:
        db.session.add(news)
        db.session.commit()
    except Exception as e:
        db.session.rollback()
        current_app.logger.error(e)
        return jsonify(errno=RET.NODATA, errmsg="未查询到数据")



    return jsonify(errno=RET.OK, errmsg="OK")





@admin_blu.route('/news_review_detail/<int:news_id>')
def news_review_detail(news_id):
    """新闻审核"""
    # 获取新闻id



    """新闻后台新闻审核详情页"""

    # 通过id查询新闻
    news = None
    try:
        news = News.query.get(news_id)
    except Exception as e:
        current_app.logger.error(e)

    if not news:
        return render_template('admin/news_review_detail.html', data={"errmsg": "未查询到此新闻"})

    # 返回数据
    data = {"news": news.to_dict()}
    return render_template('admin/news_review_detail.html', data=data)



# "新闻编辑"
@admin_blu.route('/news_edit')
@check_user
def news_edit():
    user=g.user
    try:
        page=request.args.get('p',1)
        keywords=request.args.get('keywords')
        page=int(page)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.PARAMERR,errmsg='参数错误')

    filters = [News.status == 0]
    if keywords:
        filters.append(News.title.contains(keywords))


    try:
        paginate=News.query.filter(*filters).order_by(News.create_time.desc())\
            .paginate(page,constants.ADMIN_NEWS_PAGE_MAX_COUNT,False)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR,errmsg='数据库查询错误')
    pages=paginate.pages
    news_obj_list=paginate.items
    news_list=[]
    for news in news_obj_list:
        news_list.append(news.to_dict())

    data={
        'news_list':news_list,
        'current_page':page,
        'total_page':pages

    }

    return render_template('admin/news_edit.html',data=data)

@admin_blu.route('/news_edit_detail',methods=['POST','GET'])
@check_user
def news_edit_detail():
    if request.method=='GET':
        news_id=request.args.get('news_id')

        try:
            news_id=int(news_id)
        except Exception as e:
            current_app.logger.error(e)
            return jsonify(errno=RET.PARAMERR,errmsg='参数错误')
        try:
            news_obj=News.query.filter(News.id==news_id).first()
        except Exception as e:
            current_app.logger.error(e)
            return jsonify(errno=RET.DBERR,errmsg='数据库查询失败')


        try:
            categories = Category.query.all()
        except Exception as e:
            current_app.logger.error(e)
            return render_template('admin/news_edit_detail.html', errmsg="查询数据错误")
        category_dict_li = []
        for category in categories:
            # 取到分类的字典
            cate_dict = category.to_dict()
            # 判断当前遍历到的分类是否是当前新闻的分类，如果是，则添加is_selected为true
            if category.id == news_obj.category_id:
                cate_dict["is_selected"] = True
            category_dict_li.append(cate_dict)

        category_dict_li.pop(0)

        data={
            'categories':category_dict_li,
            'news':news_obj.to_dict()
        }

        return render_template('admin/news_edit_detail.html',data=data)
    else:
        digest=request.form.get('digest')
        # index_image=request.form.get('index_image')
        content=request.form.get('content')
        category_id=request.form.get('category_id')
        news_id = request.form.get("news_id")
        title = request.form.get("title")

        if not all([digest,content,category_id,news_id,title]):
            return jsonify(errno=RET.PARAMERR,errmsg='参数不完整')


        try:
            news=News.query.get(news_id)
        except Exception as e :
            current_app.logger.error(e)
            return jsonify(errno=RET.DBERR,errmsg='数据库查询失败，详情POST')

        if not news:
            return jsonify(errno=RET.DBERR,errmsg='数据库查询失败，详情POST')

        news.title=title
        news.avatar_url=digest
        news.content=content
        news.category_id=category_id
            # news.avatar_url=image(read()后调用，storage生成avatar——url)

        try:
            db.session.add(news)
            db.session.commit()
        except Exception as e:
            db.session.rollback()
            current_app.logger.error(e)
            return jsonify(errno=RET.DBERR, errmsg="数据库存储失败")
        return jsonify(errno=RET.OK, errmsg='OK')


# "新闻类型"

info/moduls/index/__init__.py
from flask import Blueprint

index_=Blueprint('index',__name__)

from .views import *

info/moduls/index/views.py
from flask import current_app, jsonify
from flask import render_template
from flask import request
from flask import session

from info import constants
from info import redis_store
from info.models import User, News, Category
from info.utils.response_code import RET
from . import index_

@index_.route('/')
def hello_world():
    user_id=session.get('user_id',None)
    user=None
    if user_id:
        try:
            user=User.query.get(user_id)

        except Exception as e:
            current_app.logger(e)
            return jsonify(errno=RET.DBERR,errmsg='数据库查询错误User')


    try:
        news_list=News.query.order_by(News.clicks.desc()).limit(constants.CLICK_RANK_MAX_NEWS)
    except Exception as e:
        current_app.logger(e)
        return jsonify(errno=RET.DBERR, errmsg='数据库查询错误News')
    click_news_list=[]
    for news in news_list:
        news_dict=news.to_dict()
        click_news_list.append(news_dict)


    try:
        categories=Category.query.all()
    except Exception as e:
        current_app.logger(e)
        return jsonify(errno=RET.DBERR,errmsg='数据库查询错误Categories')

    categorie_list=[]
    for category in categories:

        categorie_list.append(category.to_dict())




    data={
        'user':user.to_dict() if user else None,
        'news_dict_li':click_news_list,
        'categories':categorie_list
    }
    return render_template('news/index.html',data=data)



@index_.route('/news_list')
def news_list():
    # res = request.json
    cid = request.args.get('cid',1)
    page = request.args.get('page', 1)
    per_page = request.args.get('per_page', 10)

    # if not all([res,cid,per_page]):
    #     return jsonify(errno=RET.PARAMERR,errmsg='缺少页码参数')
    #
    try:
        cid = int(cid)
        page = int(page)
        per_page = int(per_page)

    except Exception as e:
        current_app.logger(e)
        return jsonify(errno=RET.PARAMERR, errmsg='参数类型错误')

    news_list = []
    if cid!=1:
        news_list.append(News.category_id == cid)

    try:
        paginate = News.query.filter(*news_list).order_by(News.create_time.desc()).paginate(page, per_page, False)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg="数据查询错误")

    news_model_list = paginate.items  # 模型对象列表
    total_page = paginate.pages
    current_page = paginate.page

    # 将模型对象列表转成字典列表
    news_dict_li = []
    for news in news_model_list:
        news_dict_li.append(news.to_basic_dict())

    data = {
        "total_page": total_page,
        "current_page": current_page,
        "news_dict_li": news_dict_li
    }

    return jsonify(errno=RET.OK, errmsg="OK", data=data)







@index_.route('/favicon.ico')
def favicon():
    return current_app.send_static_file('news/favicon.ico')

info/moduls/news/__init__.py
from flask import Blueprint

#创建蓝图对象
news_blu = Blueprint("news", __name__, url_prefix="/news")

from . import views

info/moduls/passport/__init__.py
from flask import Blueprint

passport_=Blueprint('passport',__name__,url_prefix='/passport')

from .views import *

info/moduls/profile/__init__.py
from flask import Blueprint
from flask.ext.wtf.csrf import generate_csrf

profile_blu=Blueprint("profile", __name__, url_prefix='/user')

from . import views




# @profile_blu.after_request
# def after_request(response):
#     # 调用函数生成 csrf_token
#     csrf_token = generate_csrf()
#     # 通过 cookie 将值传给前端
#     response.set_cookie("csrf_token", csrf_token)
#     return response
# @profile_blu.before_request
# def set_csrf(response):
#     csrf_token=generate_csrf()
#     response.set_cookie()
#     return response

info/templates/news/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block titleBlock %}

    {% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="../../static/news/css/reset.css">
    <link rel="stylesheet" type="text/css" href="../../static/news/css/main.css">
    <script type="text/javascript" src="../../static/news/js/jquery-1.12.4.min.js"></script>
    <script type="text/javascript" src="../../static/news/js/main.js"></script>
    {% block scriptBlock %}

    {% endblock %}
</head>
<body>
    <div class="header_con">
        <div class="header">
            <a href="/" class="logo fl"><img src="../../static/news/images/logo.png" alt="logo"></a>
            {% block categoryBlock %}
                <ul class="menu fl">
                    {% for category in data.categories %}
                         {% if loop.index == 2 %}
                            <li data-cid="{{ category.id }}" class="active"><a href="javascript:;">{{ category.name }}</a></li>
                         {% else %}
                            <li data-cid="{{ category.id }}"><a href="javascript:;">{{ category.name }}</a></li>
                         {% endif %}
                    {% endfor %}
                </ul>
            {% endblock %}
            {% if data.user %}
                <!-- 用户登录后显示下面，隐藏上面 -->
                <div class="user_login fr">
                    <img src="{% if data.user.avatar_url %}{{ data.user.avatar_url }}{% else %}../../static/news/images/person01.png{% endif %}" class="lgin_pic">
                    <a href="/user/info">{{ data.user.nick_name }}</a>
                    <a href="javascript:;" onclick="logout()">退出</a>
                </div>

            {% else %}
                <div class="user_btns fr">
                    <a href="javascript:;" class="login_btn">登录</a> / <a href="javascript:;" class="register_btn">注册</a>
                </div>
            {% endif %}

        </div>
    </div>

    <div class="conter_con">
    {% block contentBlock %}
    {% endblock %}

    {% block authorBlock %}
        <div class="rank_con fr">
    {% endblock %}
        <div class="rank_title">
            <h3>点击排行</h3>
        </div>
        <ul class="rank_list">
            {% for new in data.news_dict_li %}
            <li><span class="{{ loop.index0 | indexClass }}">{{ loop.index }}</span><a href="/news/{{ new.id }}">{{ new.title }}</a></li>
            {% endfor %}
        </ul>
    </div>

    </div>
    <div class="footer">
        <div class="footer_links">
            <a href="">关于我们</a>
            <span>|</span>
            <a href="">联系我们</a>
            <span>|</span>
            <a href="">招聘人才</a>
            <span>|</span>
            <a href="">友情链接</a>
        </div>
        <p class="copyright">
            CopyRight © 2018 新经资讯信息技术有限公司 All Rights Reserved<br />
电话：010-****888    京ICP备*******8号
        </p>
    </div>

    <!-- 登录表单 -->
    <form class="login_form_con">
        <div class="login_form">
            <div class="login_title">
                <h3>登 录</h3>
                <a href="javascript:;" class="shutoff"></a>
            </div>
            <div class="form_group">
                <input id="mobile" type="text" name="mobile" autocomplete="off">
                <div class="input_tip">手机号</div>
                <div id="login-mobile-err" class="error_tip">手机号不能为空</div>
            </div>
            <div class="form_group">
                <input id="password" type="password" name="password">
                <div class="input_tip">密码(不少于6位)</div>
                <div id="login-password-err" class="error_tip">密码不能为空</div>
            </div>
            <input type="submit" name="" value="登 录" class="input_sub">
            <div class="down_link">还没有账号？<a href="javascript:;" class="to_register">立即注册</a></div>
        </div>
        <div class="mask"></div>
    </form>

    <!-- 注册表单 -->
    <form class="register_form_con">
        <div class="register_form">
            <div class="register_title">
                <h3>注 册</h3>
                <a href="javascript:;" class="shutoff"></a>
            </div>
            <div class="form_group">
                <input type="text" name="mobile" autocomplete="off" id="register_mobile" class="phone_input">
                <div class="input_tip">手机号</div>
                <div id="register-mobile-err" class="error_tip">手机号不能为空</div>
            </div>
            <div class="form_group">
                <input type="text" name="code_pwd" id="imagecode" class="code_pwd">
                <div class="input_tip">图形验证码</div>
                <img src="../../static/news/images/pic_code.png" class="get_pic_code" onclick="generateImageCode()">
                <div id="register-image-code-err" class="error_tip">图形码不能为空</div>
            </div>
            <div class="form_group">
                <input type="text" name="smscode" id="smscode" class="code_pwd">
                <div class="input_tip">手机验证码</div>
                <a href="javascript:;" class="get_code" onclick="sendSMSCode()">点击获取验证码</a>
                <div id="register-sms-code-err" class="error_tip">验证码不能为空</div>
            </div>
            <div class="form_group">
                <input type="password" name="password" id="register_password" class="pass_input">
                <div class="input_tip">密码(不少于6位)</div>
                <div id="register-password-err" class="error_tip">密码不能为空</div>
            </div>
            <div  class="form_group2 clearfix">
                <input type="checkbox" class="agree_input" checked>
                <p>同意使用条款，并已阅读"跟帖评论自律管理承诺书"</p>
                <div class="error_tip">请勾选</div>
            </div>
            <input type="submit" name="" value="注 册" class="input_sub">
            <div class="down_link">已有账号？<a href="javascript:;" class="to_login">立即登录</a></div>
        </div>
        <div class="mask"></div>
    </form>
</body>
</html>

info/templates/news/detail.html
{% extends 'news/base.html' %}

{% block titleBlock %}
文章详情页
{% endblock %}

{% block categoryBlock %}

{% endblock %}

{% block scriptBlock %}
<script type="text/javascript" src="../../static/news/js/detail.js"></script>
{% endblock %}

{% block contentBlock %}
 <div class="detail_con fl">
        <h3>{{ data.news.title }}</h3>

        <div class="detail_about clearfix">
            <span class="time_souce fl">{{ data.news.create_time }} 来源: {{ data.news.source }}</span>
            <span class="comment fr">{{ data.news.comments_count }}</span>
        </div>
        {{ data.news.content | safe }}

        <a href="javascript:;" class="collected block-center" data-newid="{{ data.news.id }}" style="display: {% if data.is_collected %} block
        {% else %} none {% endif %};"><span class="out">已收藏</span><span class="over">取消收藏</span></a>
        <a href="javascript:;" class="collection block-center" data-newid="{{ data.news.id }}" style="display: {% if data.is_collected %} none
        {% else %} block {% endif %};">收藏</a>

{#        <a href="javascript:;" class="collection block-center">收藏</a>#}
{#        <a href="javascript:;" class="collected block-center" style="display: none"><span class="out">已收藏</span><span class="over">取消收藏</span></a>#}


         {% if data.user %}
            <form action="" class="comment_form" data-newsid="{{ data.news.id }}">
                <div class="person_pic">
                    <img src="{% if data.user.avatar_url %}
                        {{ data.user.avatar_url }}
                    {% else %}
                        ../../static/news/images/person01.png
                    {% endif %}" alt="用户图标">
                </div>
                <textarea placeholder="请发表您的评论" class="comment_input"></textarea>
                <input type="submit" name="" value="评 论" class="comment_sub">
            </form>
        {% else %}
            <div class="comment_form_logout">
                登录发表你的评论
            </div>
        {% endif %}

        <div class="comment_count">
            {{ data.news.comments_count }}条评论
        </div>

        <div class="comment_list_con">
            {% for comment in data.comments %}
                <div class="comment_list">
                    <div class="person_pic fl">
                        <img src="{% if comment.user.avatar_url %}
                            {{ comment.user.avatar_url }}
                        {% else %}
                            ../../static/news/images/person01.png
                        {% endif %}" alt="用户图标">
                    </div>
                    <div class="user_name fl">{{ comment.user.nick_name }}</div>
                    <div class="comment_text fl">{{ comment.content }}</div>
                    {% if comment.parent %}
                        <div class="reply_text_con fl">
                            <div class="user_name2">{{ comment.parent.user.nick_name }}</div>
                            <div class="reply_text">
                                {{ comment.parent.content }}
                            </div>
                        </div>
                    {% endif %}
                    <div class="comment_time fl">{{ comment.create_time }}</div>
{#                    <a href="javascript:;" class="comment_up fr" data-commentid="{{ comment.id }}" data-newsid="{{ comment.news_id }}">赞</a>#}
                    <a href="javascript:;" class="comment_up
                        {% if comment.is_like %}
                            has_comment_up
                        {% endif %} fr"
                           data-commentid="{{ comment.id }}"
                           data-likecount="{{ comment.like_count }}"
                           data-newsid="{{ data.news.id }}">
                        {% if comment.like_count > 0 %}
                            {{ comment.like_count }}
                        {% else %}
                            赞
                        {% endif %}
                    </a>
                    <a href="javascript:;" class="comment_reply fr">回复</a>
                    <form class="reply_form fl" data-commentid="{{ comment.id }}" data-newsid="{{ data.news.id }}">
                        <textarea class="reply_input"></textarea>
                        <input type="button" value="回复" class="reply_sub fr">
                        <input type="reset" name="" value="取消" class="reply_cancel fr">
                    </form>
                </div>
            {% endfor %}
        </div>

 </div>

{% endblock %}

{% block authorBlock %}
<div class="author_card">
    <a href="#" class="author_pic"><img src="../../static/news/images/user_pic.png" alt="author_pic"></a>
    <a href="#" class="author_name">张大山</a>
    <div class="author_resume">张大山的简介,张大山</div>
    <div class="writings"><span>总篇数</span><b>23</b></div>
    <div class="follows"><span>粉丝</span><b>36</b></div>
    <a href="javascript:;" class="focus fr">关注</a>
    <a href="javascript:;" class="focused fr"><span class="out">已关注</span><span class="over">取消关注</span></a>
</div>
{% endblock %}

info/templates/news/index.html
{% extends 'news/base.html' %}

{% block titleBlock %}
首页-新经资讯
{% endblock %}

{% block news_list %}
{% endblock %}

{% block  scriptBlock %}
    <script type="text/javascript" src="../../static/news/js/index.js"></script>
{% endblock %}


{#{% block categoryBlock %}#}
{#1#}
{#{% endblock %}#}


{% block contentBlock %}
<ul class="list_con fl">

</ul>
{% endblock %}

info/templates/news/user.html
{% extends 'news/base.html' %}

{% block titleBlock %}

 
用户中心

 
{% endblock %}

 


 
{% block authorBlock %}

 
{% endblock %}

{% block rankBlock %}

{% endblock %}

{% block contentBlock %}
<div class="user_menu_con fl">
    <div class="user_center_pic">
        <img src={% if data.user.avatar_url %}

 
            {{ data.user.avatar_url }}

 
        {% else %}

 
            "../../static/news/images/user_pic.png"

 
        {% endif %} alt="用户图片">

 
    </div>

 
    <div class="user_center_name">{{ data.user.nick_name }}</div>

 


 
    <ul class="option_list">

 
        <li class="active"><a href="{{ url_for('profile.user_base_info') }}" target="main_frame">基本资料</a></li>

 
        <li><a href=" {{ url_for("profile.pic_info") }}" target="main_frame">头像设置</a></li>

 
        <li><a href="../../static/news/html/user_follow.html" target="main_frame">我的关注</a></li>

 
        <li><a href="{{ url_for("profile.pass_info") }}" target="main_frame">密码修改</a></li>


 
        <li><a href="{{ url_for("profile.user_collection") }}" target="main_frame">我的收藏</a></li>

 
        <li><a href="{{ url_for("profile.news_release") }}" target="main_frame">新闻发布</a></li>

 
        <li><a href="{{ url_for("profile.news_list") }}" target="main_frame">新闻列表</a></li>

 
    </ul>

 
</div>

 


 
<div class="user_con fr">

 
    <iframe src={{ url_for('profile.user_base_info') }} frameborder="0" name="main_frame" class="main_frame" id="main_frame"></iframe>

 
</div>

 
{% endblock %}

 


 
 
{% block categoryBlock %}

 
{% endblock %}